services:
  web:
    container_name: CarCostPredictorWeb
    build:
      context: .
      dockerfile: ./dockerfile
    # Запускаем тестовый сервер
    command: uvicorn app:app --host 0.0.0.0
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000